### PR TITLE
Improved header layout and responsiveness in mobile devices

### PR DESCRIPTION
**Pull request by kushal7201**
Issue: #2 
In desktop:
brave_351vm6GR9r

In Mobile Devices:
brave_YoGtJvGmwh

### CODE REVIEW

**Comment by manzil-infinity180** [comment]
uncomment the about me then I will merge it

**Comment by kushal7201** [comment]
@manzil-infinity180  I have made the requested change. Kindly review.

**Comment by manzil-infinity180** [comment]
how it looks now ?

**Comment by kushal7201** [comment]
@manzil-infinity180 
For Desktop:
brave_G1jl2YbHha

For Mobile:
brave_DMuQb8wETS

**Review by manzil-infinity180 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
