### PR TITLE
BUG: Without login it navigate to home page instead of Error Page

### LINKED ISSUE #4: If not login redirect to home page
Currently when i click on `my profile`(navbar) it start loading what i mean if user is not logined then do not show the profile text on navbar 

https://github.com/user-attachments/assets/499f3c14-9e29-42f4-87ef-71436f4940e9

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #4 When user try to access my-profile page without login so it fetch data from backend and in case of error it redirect to home page using navigate hook and simply return from that function.

**Testing:**

https://github.com/user-attachments/assets/100091a5-e804-4eac-b1da-6d2838a859b6

@manzil-infinity180  Please review my PR and merge accordingly:)

### CODE REVIEW

**Comment by manzil-infinity180** [comment]
Add new behaviour video

**Comment by harshbhar0629** [comment]
Done Video @manzil-infinity180

**Comment by harshbhar0629** [comment]
@manzil-infinity180 any correction??

**Comment by manzil-infinity180** [comment]
I didn't see any improvement their , please read issue properly and if you have any problem ask me

**Pull request closed without merging**
