### PR TITLE
Ring loader

### PR DESCRIPTION
**Pull request by GovindSharma0708**
#3 added ring-loader and removed the infinite custom loader please review and merge pr @manzil-infinity180

### CODE REVIEW

**Comment by manzil-infinity180** [comment]
Demo ?

**Comment by GovindSharma0708** [comment]
image
 this is the demo of the new ring loader  @manzil-infinity180

**Comment by manzil-infinity180** [comment]
Didn't like the UI , and same reason for this pr too it contain the commit of header

**Comment by GovindSharma0708** [comment]
okay i will revert back all the changes and do it with different branches @manzil-infinity180

**Comment by manzil-infinity180** [comment]
Create some unique from here https://loading.io/ which fit with the current UI and make fresh pr for this too

**Comment by GovindSharma0708** [comment]
okay sir

**Comment by GovindSharma0708** [comment]
> Create some unique from here https://loading.io/ which fit with the current UI and make fresh pr for this too

will add `react-spinners` in it as it is more easily available and free to use which rely better on your project.

**Pull request closed without merging**
