### PR TITLE
Header

### PR DESCRIPTION
**Pull request by GovindSharma0708**
Changed to className and styled css of unordered list from tailwind to normal css .Please review pull request if any more changes needed give me feedback.
image

### CODE REVIEW

**Comment by GovindSharma0708** [comment]
@manzil-infinity180  i have solved both the issue of adding link to about me and adding loader please merge both issue with this pull request

**Comment by manzil-infinity180** [comment]
This is not a way to contribute why you are merging all the things in one pr 

Create separate pr

**Comment by manzil-infinity180** [comment]
This pr is related to header , for about me pr create new pr and revert the commit

**Comment by manzil-infinity180** [comment]
It is already done by some one  #17

Work on some other issue

**Comment by GovindSharma0708** [comment]
okay sir

**Pull request closed without merging**
